<?php
include_once 'Point2D.php';

class Point3D extends Point2D
{
    public $zCoordinate;

    public function __construct($xCoordinate, $yCoordinate, $zCoordinate)
    {
        parent::__construct($xCoordinate, $yCoordinate);
        $this->zCoordinate = $zCoordinate;
    }

    public function getZ()
    {
        return $this->zCoordinate;
    }

    public function setZ($zCoordinate)
    {
        $this->zCoordinate = $zCoordinate;
    }

    public function getXYZ()
    {
        $arrChild = parent::getXY();
        array_push($arrChild, $this->getZ());
        return $arrChild;
    }
    public function setXYZ($xCoordinate, $yCoosdinate, $zCoordinste)
    {
       parent::setXY($xCoordinate,$yCoosdinate);
        $this->zCoordinate = $zCoordinste;
    }

    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo " , z= $this->zCoordinate";
    }
}